---
# tasks el (rhel/CentOS/Fedora/AmazonLinux)
- name: Check nedded variables
  fail:
    msg: "You need to set a value for ansible_zabbix_agent__ServerAddr"
  when: ansible_zabbix_agent__ServerAddr is undefined

- name: Configure Zabbix Repository on (el)
  yum:
    name: "https://repo.zabbix.com/zabbix/{{ ansible_zabbix_agent__version }}/rhel/{{ ansible_distribution_major_version }}/x86_64/zabbix-release-{{ ansible_zabbix_agent__release }}.el{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
  notify: restart_zabbix_agent_el{{ ansible_distribution_major_version }}

- name: Install Zabbix Agent on (el)
  yum:
    name: "{{ ansible_zabbix_agent__packages }}"
    state: latest
    update_cache: yes
  notify: restart_zabbix_agent_el{{ ansible_distribution_major_version }}

- name: Remove default agent.d mysql user parameter file
  file:
    name: /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
    state: absent

- name: copy zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_zabbix_agent_el{{ ansible_distribution_major_version }}

- name: Ensure zabbix_agent is set on boot time (el)
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started
  when: >
    (ansible_distribution_major_version == '7')

- name: Ensure zabbix_agent is set on boot time (el)
  service:
    name: zabbix-agent
    enabled: yes
    state: started
  when: >
    (ansible_distribution_major_version == '6')

