---
# tasks file for ansible-zabbix-agent
- name: Check nedded variables
  fail:
    msg: "You need to set a value for ansible_zabbix_agent__ServerAddr"
  when: ansible_zabbix_agent__ServerAddr is undefined

- name: Configure Zabbix Repository on EL
  yum:
    name: "{{ ansible_zabbix_agent__repourl }}"
    state: present

- name: Install Zabbix Agent on EL
  yum:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - "{{ ansible_zabbix_agent__packages }}"

- name: Remove default agent.d mysql user parameter file
  file:
    name: /etc/zabbix/zabbix_agentd.d/userparameter_mysql.conf
    state: absent

- name: copy zabbix_agentd.conf
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart_zabbix_agent_el7

- name: Ensure zabbix_agent is set on boot time (EL7)
  systemd:
    name: zabbix-agent
    enabled: yes
    state: started
