---
# MAIN ANSIBLE TASK
- import_tasks: tasks/el7.yml
  when: (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and (ansible_distribution_major_version == '7')
- import_tasks: tasks/el6.yml
  when: (((ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux') and (ansible_distribution_major_version == '6')) or (ansible_distribution == 'Amazon'))
