---
# MAIN ANSIBLE TASK
- import_tasks: tasks/el.yml
  when: >
    (ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux')

- import_tasks: tasks/sles.yml
  when: (ansible_os_family == 'Suse' )
