---
# handlers file for ansible-zabbix-agent
- name: restart_zabbix_agent_el7
  systemd:
    name: zabbix-agent
    state: restarted


- name: restart_zabbix_agent_el6
  service:
    name: zabbix-agent
    state: restarted
